name: tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  selenium:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - run: mvn -B -ntp test -Dheadless=true
